algos_sps = \
{'Random Hill Climbing': {'rhc_combo1': {'seed': 1,
                                         'lengthFP': 4,
                                         'lengthFF': 4,
                                         'max_item_countKS': 6},
                          'rhc_combo2': {'seed': 1,
                                         'lengthFP': 6,
                                         'lengthFF': 6,
                                         'max_item_countKS': 8},
                          'rhc_combo3': {'seed': 1,
                                         'lengthFP': 8,
                                         'lengthFF': 8,
                                         'max_item_countKS': 10},
                          'rhc_combo4': {'seed': 2,
                                         'lengthFP': 4,
                                         'lengthFF': 4,
                                         'max_item_countKS': 6},
                          'rhc_combo5': {'seed': 2,
                                         'lengthFP': 6,
                                         'lengthFF': 6,
                                         'max_item_countKS': 8},
                          'rhc_combo6': {'seed': 2,
                                         'lengthFP': 8,
                                         'lengthFF': 8,
                                         'max_item_countKS': 10},
                          'rhc_combo7': {'seed': 3,
                                         'lengthFP': 4,
                                         'lengthFF': 4,
                                         'max_item_countKS': 6},
                          'rhc_combo8': {'seed': 3,
                                         'lengthFP': 6,
                                         'lengthFF': 6,
                                         'max_item_countKS': 8},
                          'rhc_combo9': {'seed': 3,
                                         'lengthFP': 8,
                                         'lengthFF': 8,
                                         'max_item_countKS': 10}},
 'Simulated Annealing': {'sa_combo1': {'seed': 1,
                                        'lengthFP': 4,
                                        'lengthFF': 4,
                                        'max_item_countKS': 6},
                          'sa_combo2': {'seed': 1,
                                        'lengthFP': 6,
                                        'lengthFF': 6,
                                        'max_item_countKS': 8},
                          'sa_combo3': {'seed': 1,
                                        'lengthFP': 8,
                                        'lengthFF': 8,
                                        'max_item_countKS': 10},
                          'sa_combo4': {'seed': 2,
                                        'lengthFP': 4,
                                        'lengthFF': 4,
                                        'max_item_countKS': 6},
                          'sa_combo5': {'seed': 2,
                                        'lengthFP': 6,
                                        'lengthFF': 6,
                                        'max_item_countKS': 8},
                          'sa_combo6': {'seed': 2,
                                        'lengthFP': 8,
                                        'lengthFF': 8,
                                        'max_item_countKS': 10},
                          'sa_combo7': {'seed': 3,
                                        'lengthFP': 4,
                                        'lengthFF': 4,
                                        'max_item_countKS': 6},
                          'sa_combo8': {'seed': 3,
                                        'lengthFP': 6,
                                        'lengthFF': 6,
                                        'max_item_countKS': 8},
                          'sa_combo9': {'seed': 3,
                                        'lengthFP': 8,
                                        'lengthFF': 8,
                                        'max_item_countKS': 10}},
 'Genetic Algorithm': {'ga_combo1': {'seed': 1,
                                     'lengthFP': 4,
                                     'lengthFF': 4,
                                     'max_item_countKS': 6},
                       'ga_combo2': {'seed': 1,
                                     'lengthFP': 6,
                                     'lengthFF': 6,
                                     'max_item_countKS': 8},
                       'ga_combo3': {'seed': 1,
                                     'lengthFP': 8,
                                     'lengthFF': 8,
                                     'max_item_countKS': 10},
                       'ga_combo4': {'seed': 2,
                                     'lengthFP': 4,
                                     'lengthFF': 4,
                                     'max_item_countKS': 6},
                       'ga_combo5': {'seed': 2,
                                     'lengthFP': 6,
                                     'lengthFF': 6,
                                     'max_item_countKS': 8},
                       'ga_combo6': {'seed': 2,
                                     'lengthFP': 8,
                                     'lengthFF': 8,
                                     'max_item_countKS': 10},
                       'ga_combo7': {'seed': 3,
                                     'lengthFP': 4,
                                     'lengthFF': 4,
                                     'max_item_countKS': 6},
                       'ga_combo8': {'seed': 3,
                                     'lengthFP': 6,
                                     'lengthFF': 6,
                                     'max_item_countKS': 8},
                       'ga_combo9': {'seed': 3,
                                     'lengthFP': 8,
                                     'lengthFF': 8,
                                     'max_item_countKS': 10}},
 'MIMIC': {'mmic_combo1': {'seed': 1,
                          'lengthFP': 4,
                          'lengthFF': 4,
                          'max_item_countKS': 6},
           'mmic_combo2': {'seed': 1,
                          'lengthFP': 6,
                          'lengthFF': 6,
                          'max_item_countKS': 8},
           'mmic_combo3': {'seed': 1,
                          'lengthFP': 8,
                          'lengthFF': 8,
                          'max_item_countKS': 10},
           'mmic_combo4': {'seed': 2,
                          'lengthFP': 4,
                          'lengthFF': 4,
                          'max_item_countKS': 6},
           'mmic_combo5': {'seed': 2,
                          'lengthFP': 6,
                          'lengthFF': 6,
                          'max_item_countKS': 8},
           'mmic_combo6': {'seed': 2,
                          'lengthFP': 8,
                          'lengthFF': 8,
                          'max_item_countKS': 10},
           'mmic_combo7': {'seed': 3,
                          'lengthFP': 4,
                          'lengthFF': 4,
                          'max_item_countKS': 6},
           'mmic_combo8': {'seed': 3,
                          'lengthFP': 6,
                          'lengthFF': 6,
                          'max_item_countKS': 8},
           'mmic_combo9': {'seed': 3,
                          'lengthFP': 8,
                          'lengthFF': 8,
                          'max_item_countKS': 10}}}


def main():
    import numpy as np
    for algo, combos in algos_sps.items():
        for combo, seed_size in combos.items():
            seed_size_keys = list(seed_size)
            seed = seed_size[seed_size_keys[0]]
            lengthFP =seed_size[seed_size_keys[1]]
            lengthFF = seed_size[seed_size_keys[2]]
            max_item_countKS = seed_size[seed_size_keys[3]]

            print(seed)
            print(lengthFP)
            print(lengthFF)
            print(max_item_countKS)
            
if __name__ == "__main__":
    main()